version: '3.7'

services:
  redis:
    image: redis:alpine
    restart: always

  searxng:
    image: paulgoio/searxng:{ENV}
    restart: always
    networks:
      - default
      - proxy
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    environment:
      - LIMITER2=true
      - REDIS_URL=redis://redis:6379/0
      - IMAGE_PROXY=true
      - BASE_URL=https://{DOMAIN}/
      - NAME=PaulGO
      - CONTACT=https://about.paulgo.io/#about
      - ISSUE_URL=https://github.com/paulgoio/searxng/issues
      - GIT_URL=https://github.com/paulgoio/searxng
      - GIT_BRANCH=main
    labels:
      - traefik.enable=true
      - traefik.http.routers.{REPO}.rule=Host(`{DOMAIN}`)&&Method(`GET`,`POST`,`HEAD`)
      - traefik.http.routers.{REPO}.entrypoints=https
      - traefik.http.routers.{REPO}.tls=true
      - traefik.http.routers.{REPO}.middlewares=external-secure,searx-csp@file,{REPO}-headers
      # CSP for SearXNG in dynamic config
      # feature policy for SearXNG and disable browser caching
      - traefik.http.middlewares.{REPO}-headers.headers.customResponseHeaders.Permissions-Policy=accelerometer=();ambient-light-sensor=(); autoplay=();camera=();encrypted-media=();focus-without-user-activation=(); geolocation=();gyroscope=();magnetometer=();microphone=();midi=();payment=();picture-in-picture=(); speaker=();sync-xhr=();usb=();vr=()
      - traefik.http.middlewares.{REPO}-headers.headers.customResponseHeaders.Cache-Control=no-cache
networks:
  proxy:
    external: true
